type = "javascript"

account_id = ""
workers_dev = true

compatibility_date = "2022-02-11"
compatibility_flags = []

kv_namespaces = [ 
  { binding = "SESSIONS", id = "8f972cab743647288e47bf12a11b8e66" }
]

[durable_objects]
bindings = [
  { name = "WEBSOCKETS", class_name = "WebSocketStore" }
]

[[migrations]]
tag = "v1"
new_classes = ["WebSocketStore"]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
durable_objects_persist = true

[env.staging]
name = "webhook-typer-staging"
route = "webhook-typer-staging.inngest.workers.dev/*"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "webhook-typer"
route = "webhook-typer.inngest.workers.dev/*"
vars = { ENVIRONMENT = "production" }